# Generated by Django 3.2.12 on 2024-03-02 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('branch', models.CharField(max_length=50)),
                ('rollno', models.CharField(max_length=20)),
                ('year_of_passout', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_interview', models.IntegerField()),
                ('role', models.CharField(max_length=100)),
                ('brief_description', models.TextField(blank=True, null=True)),
                ('selection_procedure', models.TextField()),
                ('online_test_desc', models.TextField(blank=True, null=True)),
                ('tech_interview_desc', models.TextField()),
                ('hr_interview_desc', models.TextField()),
                ('prep_resources', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appi.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appi.userdetails')),
            ],
        ),
    ]
