# Generated by Django 3.2.12 on 2024-02-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('linkedin_profile', models.URLField(blank=True)),
                ('branch', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=100)),
                ('year_of_passout', models.IntegerField()),
                ('company_name', models.CharField(max_length=100)),
                ('year_of_interview', models.IntegerField()),
                ('role', models.CharField(max_length=100)),
                ('brief_description', models.TextField(blank=True)),
                ('selection_procedure', models.TextField()),
                ('online_test_description', models.TextField()),
                ('technical_round_description', models.TextField()),
                ('hr_round_description', models.TextField(blank=True)),
                ('resources_for_preparation', models.TextField(blank=True)),
                ('contact_no', models.CharField(blank=True, max_length=100)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
