# Generated by Django 3.2.12 on 2024-03-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0002_discussion_forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
